### ISSUE TITLE
timestamps not being added

### ISSUE THREAD

**Issue by si458** [Ylianst/Authenticode-JS#1]
Hi,
not sure if its a bug or me being stupid,
it signs correctly but the timestamps are missing?
both in the signature list AND the signer information sections?
also the countersignatures is blank too?
```
node authenticode.js sign --exe /opt/meshcentral/meshcentral-data/signedagents/MeshService64.exe --out /opt/meshcentral/meshcentral-data/signedagents/MeshService64out.exe --pem /opt/meshcentral/meshcentral-data/mycert/trythis.pem --url http://timestamp.comodoca.com
```

**Comment by Ylianst** [comment]
Ha yes. Authenticode-JS does not currently support signed timestamps. Certainly something I was at add since I timestamp all the signed executable. I have not investigated this yet. Right now, I am working a lot of being able to edit resources within the exe file.

**Comment by si458** [comment]
@Ylianst thats perfectly fine no rush,
the timestamps just help with renewal of the code-sign certificates, so the exes can carry on without re-signing again
(our certificate expires in 6 months time haha, so renewal will be fun!)

**Comment by Ylianst** [comment]
Yes exactly. Time stamping allows the OS to validate a executable even if your cert is expired, this is exactly why it's very important.

**Comment by Ylianst** [comment]
For my own use later, [Microsoft details on this topic are here](https://docs.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures).

**Comment by Ylianst** [comment]
Just did a commit that adds time-stamping support.

**Comment by Ylianst** [comment]
[v1.0.4 is out on NPM](https://www.npmjs.com/package/authenticode-js)

![MC2-AuthenticodeTimeStamp](https://user-images.githubusercontent.com/1319013/174448663-2102b710-1434-4db1-a068-32ae936062e6.png)

**Comment by Ylianst** [comment]
I will close this since it's fixed. Do open a new issue if something is not right.
